name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v5
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: yarn

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for GPR
        uses: actions/setup-node@v5
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@snazzah'

      - run: npm install
      - run: npm run gpr
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}